[dependencies]

[package]
name = "Strings"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "01_compararStrings"
path = "01_compararStrings.rs"

[[bin]]
name = "02_NomeAoContrario"
path = "02_NomeAoContrario.rs"

